# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38950b100fd9c7355bd854260043ada3e374f04c2f0d333332311bad6cfc796f65e0fd37ec01e3ef8e7e233eeeab293c245abdfc260eef8ac30238e62f5c257

test:
  secret_key_base: 6d061ab68916404059bc112342175ced1b1e8efd5b5b8278513dba6bdb56677bf10ae450464766fbc12e67fed873c9b8f5916de8b494c58e0783dbf8f20c9a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
